
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import dal.ConectionModule;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.table.DefaultTableModel;
import static mondrian.olap.fun.vba.Vba.str;

/*
 * Bruno H. M. Mendanha
 * ID: 20325
 * e-mail: bmendanha@hotmail.com
 */
public class LecturerAttendance extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form frmAdmin
     */
    public LecturerAttendance() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        conexao = ConectionModule.conector();
        eraseFieldsMain();
        carregaTabelaStudent();
        carregaTabelaSubject();

        // carregaTabelaAttendance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNameStudent = new javax.swing.JTextField();
        txtTitleSubject = new javax.swing.JTextField();
        txtIdStudent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbSubject = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSurnameStudent = new javax.swing.JTextField();
        txtIdSubject = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtIdAttendance = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAttendance = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtw1 = new javax.swing.JTextField();
        txtw2 = new javax.swing.JTextField();
        txtw3 = new javax.swing.JTextField();
        txtw4 = new javax.swing.JTextField();
        txtw5 = new javax.swing.JTextField();
        txtw6 = new javax.swing.JTextField();
        txtw7 = new javax.swing.JTextField();
        txtw8 = new javax.swing.JTextField();
        txtw9 = new javax.swing.JTextField();
        txtw10 = new javax.swing.JTextField();
        txtw11 = new javax.swing.JTextField();
        txtw12 = new javax.swing.JTextField();
        txtw13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtw14 = new javax.swing.JTextField();
        txtw15 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnEraseFields = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAdminStudent3 = new javax.swing.JButton();
        btnAdminFaculty3 = new javax.swing.JButton();
        btnAdminBranch9 = new javax.swing.JButton();
        btnExit3 = new javax.swing.JButton();
        btnAdminBranch10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lecturer Access");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setText("Student");

        jLabel7.setText("Subject");

        jLabel1.setText("ID Student");

        tbStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStudentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbStudent);
        if (tbStudent.getColumnModel().getColumnCount() > 0) {
            tbStudent.getColumnModel().getColumn(0).setResizable(false);
            tbStudent.getColumnModel().getColumn(1).setResizable(false);
            tbStudent.getColumnModel().getColumn(2).setResizable(false);
        }

        tbSubject.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tbSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSubject.getTableHeader().setReorderingAllowed(false);
        tbSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSubjectMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbSubject);
        if (tbSubject.getColumnModel().getColumnCount() > 0) {
            tbSubject.getColumnModel().getColumn(0).setResizable(false);
            tbSubject.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbSubject.getColumnModel().getColumn(1).setResizable(false);
            tbSubject.getColumnModel().getColumn(1).setPreferredWidth(20);
        }

        jLabel2.setText("Surname");

        txtSurnameStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurnameStudentActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Generated code:");

        txtIdAttendance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtIdAttendance.setForeground(new java.awt.Color(0, 0, 153));
        txtIdAttendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbAttendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tbAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Attendance", "ID Student", "Name", "Surname", "Subject", "W1", "W2", "W3", "W4", "W5", "W6", "W7", "W8", "W9", "W10", "W11", "W12", "W13", "W14", "W15"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAttendance.setColumnSelectionAllowed(true);
        tbAttendance.getTableHeader().setReorderingAllowed(false);
        tbAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAttendanceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAttendance);
        tbAttendance.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tbAttendance.getColumnModel().getColumnCount() > 0) {
            tbAttendance.getColumnModel().getColumn(0).setResizable(false);
            tbAttendance.getColumnModel().getColumn(1).setResizable(false);
            tbAttendance.getColumnModel().getColumn(2).setResizable(false);
            tbAttendance.getColumnModel().getColumn(3).setResizable(false);
            tbAttendance.getColumnModel().getColumn(4).setResizable(false);
            tbAttendance.getColumnModel().getColumn(5).setResizable(false);
            tbAttendance.getColumnModel().getColumn(5).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(6).setResizable(false);
            tbAttendance.getColumnModel().getColumn(6).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(7).setResizable(false);
            tbAttendance.getColumnModel().getColumn(7).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(8).setResizable(false);
            tbAttendance.getColumnModel().getColumn(8).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(9).setResizable(false);
            tbAttendance.getColumnModel().getColumn(9).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(10).setResizable(false);
            tbAttendance.getColumnModel().getColumn(10).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(11).setResizable(false);
            tbAttendance.getColumnModel().getColumn(11).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(12).setResizable(false);
            tbAttendance.getColumnModel().getColumn(12).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(13).setResizable(false);
            tbAttendance.getColumnModel().getColumn(13).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(14).setResizable(false);
            tbAttendance.getColumnModel().getColumn(14).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(15).setResizable(false);
            tbAttendance.getColumnModel().getColumn(15).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(16).setResizable(false);
            tbAttendance.getColumnModel().getColumn(16).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(17).setResizable(false);
            tbAttendance.getColumnModel().getColumn(17).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(18).setResizable(false);
            tbAttendance.getColumnModel().getColumn(18).setPreferredWidth(30);
            tbAttendance.getColumnModel().getColumn(19).setResizable(false);
            tbAttendance.getColumnModel().getColumn(19).setPreferredWidth(30);
        }

        jLabel5.setText("W1");

        jLabel8.setText("W8");

        jLabel9.setText("W2");

        jLabel10.setText("W3");

        jLabel11.setText("W4");

        jLabel12.setText("W5");

        jLabel13.setText("W6");

        jLabel14.setText("W7");

        jLabel15.setText("W9");

        txtw1.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw2.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw3.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw4.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw5.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw6.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw7.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw8.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw9.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw10.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw11.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw12.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw13.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel16.setText("W10");

        jLabel17.setText("W11");

        jLabel18.setText("W12");

        jLabel19.setText("W13");

        jLabel20.setText("W14");

        jLabel21.setText("W15");

        txtw14.setPreferredSize(new java.awt.Dimension(25, 25));

        txtw15.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitleSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(txtIdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSurnameStudent)
                            .addComponent(txtNameStudent)
                            .addComponent(txtIdSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtw1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtw3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtw4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtw5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtw6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtw7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtw8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtw9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txtw10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtw11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txtw12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txtw13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txtw14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtw15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(5, 5, 5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtSurnameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtIdSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTitleSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel8)
                                .addComponent(jLabel15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtw10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtw11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtw12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtw13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtw15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtw5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save32px.png"))); // NOI18N
        btnSave.setToolTipText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEraseFields.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/erase32px.png"))); // NOI18N
        btnEraseFields.setToolTipText("Erase Fields");
        btnEraseFields.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEraseFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraseFieldsActionPerformed(evt);
            }
        });

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print32px.png"))); // NOI18N
        btnPrint.setToolTipText("Print");
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete32px.png"))); // NOI18N
        btnDelete.setToolTipText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VGC -Attendance");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEraseFields, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEraseFields, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAdminStudent3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/presence48px.png"))); // NOI18N
        btnAdminStudent3.setToolTipText("Presence");
        btnAdminStudent3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminStudent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminStudent3ActionPerformed(evt);
            }
        });

        btnAdminFaculty3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grade48px.png"))); // NOI18N
        btnAdminFaculty3.setToolTipText("Grade");
        btnAdminFaculty3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminFaculty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminFaculty3ActionPerformed(evt);
            }
        });

        btnAdminBranch9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/assessment00.png"))); // NOI18N
        btnAdminBranch9.setToolTipText("Assessment");
        btnAdminBranch9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminBranch9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminBranch9ActionPerformed(evt);
            }
        });

        btnExit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit48px.png"))); // NOI18N
        btnExit3.setToolTipText("Exit");
        btnExit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit3ActionPerformed(evt);
            }
        });

        btnAdminBranch10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact48px.png"))); // NOI18N
        btnAdminBranch10.setToolTipText("Contact");
        btnAdminBranch10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminBranch10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminBranch10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdminBranch10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminFaculty3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminStudent3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminBranch9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdminStudent3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminFaculty3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminBranch9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminBranch10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnExit3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveAttendance();
        carregaTabelaStudent();
        carregaTabelaSubject();
        carregaTabelaAttendance();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void saveAttendance() {
        txtIdAttendance.setText(txtIdStudent.getText() + txtIdSubject.getText());
        String sql = "insert into attendance(idAttendance,IdStudent,firstNameStudent,lastNameStudent,IdSubject,titleSubject,w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,w14,w15)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtIdAttendance.getText());
            pst.setString(2, txtIdStudent.getText());
            pst.setString(3, txtNameStudent.getText());
            pst.setString(4, txtSurnameStudent.getText());
            pst.setString(5, txtIdSubject.getText());
            pst.setString(6, txtTitleSubject.getText());
            pst.setString(7, txtw1.getText());
            pst.setString(8, txtw2.getText());
            pst.setString(9, txtw3.getText());
            pst.setString(10, txtw4.getText());
            pst.setString(11, txtw5.getText());
            pst.setString(12, txtw6.getText());
            pst.setString(13, txtw7.getText());
            pst.setString(14, txtw8.getText());
            pst.setString(15, txtw9.getText());
            pst.setString(16, txtw10.getText());
            pst.setString(17, txtw11.getText());
            pst.setString(18, txtw12.getText());
            pst.setString(19, txtw13.getText());
            pst.setString(20, txtw14.getText());
            pst.setString(21, txtw15.getText());
            //the line below updates table ATTENDANCE with the form data.
            int adicionado = pst.executeUpdate();
            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "the ATTENDANCE was saved with success");
                eraseFieldsMain();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "This STUDENT has already been ALOCATED to this class  \n" + e);
            eraseFieldsMain();
        }
    }

    private void carregaTabelaStudent() {
        DefaultTableModel modelo = (DefaultTableModel) tbStudent.getModel();
        modelo.setNumRows(0);
        tbStudent.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbStudent.getColumnModel().getColumn(1).setPreferredWidth(50);
        tbStudent.getColumnModel().getColumn(2).setPreferredWidth(50);
        try {
            pst = conexao.prepareStatement("select idStudent,firstNameStudent,lastNameStudent from students order by firstNameStudent;");
            rs = pst.executeQuery();
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),});
            }

        } catch (Exception e) {
        }
    }

    private void carregaTabelaSubject() {
        DefaultTableModel modelo = (DefaultTableModel) tbSubject.getModel();
        modelo.setNumRows(0);
        tbSubject.getColumnModel().getColumn(0).setPreferredWidth(20);
        tbSubject.getColumnModel().getColumn(1).setPreferredWidth(50);

        try {
            pst = conexao.prepareStatement("select IdSubject, titleSubject from subjects order by titleSubject;");
            rs = pst.executeQuery();
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2)
                });
            }

        } catch (Exception e) {

        }
    }

    private void carregaTabelaAttendance() {
        DefaultTableModel modelo = (DefaultTableModel) tbAttendance.getModel();
        modelo.setNumRows(0);
        tbAttendance.getColumnModel().getColumn(0).setPreferredWidth(20);
        tbAttendance.getColumnModel().getColumn(1).setPreferredWidth(30);
        tbAttendance.getColumnModel().getColumn(2).setPreferredWidth(30);
        tbAttendance.getColumnModel().getColumn(3).setPreferredWidth(40);
        tbAttendance.getColumnModel().getColumn(4).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(5).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(6).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(5).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(6).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(7).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(8).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(9).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(10).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(11).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(12).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(13).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(14).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(15).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(16).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(17).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(18).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(19).setPreferredWidth(5);
        tbAttendance.getColumnModel().getColumn(20).setPreferredWidth(5);

        try {
            pst = conexao.prepareStatement("idAttendance,IdStudent,firstNameStudent,lastNameStudent,IdSubject,titleSubject,w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,w14,w15 order by firstNameStudent;");
            rs = pst.executeQuery();
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(10),
                    rs.getString(11),
                    rs.getString(12),
                    rs.getString(13),
                    rs.getString(14),
                    rs.getString(15),
                    rs.getString(16),
                    rs.getString(17),
                    rs.getString(18),
                    rs.getString(19),
                    rs.getString(20),
                    rs.getString(21)
                });
            }

        } catch (Exception e) {
        }
    }

    private void eraseFieldsMain() {
        txtIdStudent.setText(null);
        txtNameStudent.setText(null);
        txtSurnameStudent.setText(null);
        txtIdSubject.setText(null);
        txtTitleSubject.setText(null);
        txtIdAttendance.setText(null);
    }

    public void setar_camposSt() {
        int setar = tbStudent.getSelectedRow();
        txtIdStudent.setText(tbStudent.getModel().getValueAt(setar, 0).toString());
        txtNameStudent.setText(tbStudent.getModel().getValueAt(setar, 1).toString());
        txtSurnameStudent.setText(tbStudent.getModel().getValueAt(setar, 2).toString());

    }

    public void setar_camposAs() {
        int setar = tbSubject.getSelectedRow();
        txtIdSubject.setText(tbSubject.getModel().getValueAt(setar, 0).toString());
        txtTitleSubject.setText(tbSubject.getModel().getValueAt(setar, 1).toString());

    }

    public void setar_camposGr() {
        int setar = tbAttendance.getSelectedRow();
        txtIdAttendance.setText(tbAttendance.getModel().getValueAt(setar, 0).toString());
        txtNameStudent.setText(tbAttendance.getModel().getValueAt(setar, 1).toString());
        txtSurnameStudent.setText(tbAttendance.getModel().getValueAt(setar, 2).toString());
        txtTitleSubject.setText(tbAttendance.getModel().getValueAt(setar, 3).toString());

    }

    private void btnEraseFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraseFieldsActionPerformed
        eraseFieldsMain();
        txtIdStudent.setVisible(true);
        txtNameStudent.setVisible(true);
        txtSurnameStudent.setVisible(true);
        txtIdSubject.setVisible(true);
        txtTitleSubject.setVisible(true);
        tbStudent.setVisible(true);
        tbSubject.setVisible(true);
    }//GEN-LAST:event_btnEraseFieldsActionPerformed


    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteGrade();
        carregaTabelaAttendance();
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void deleteGrade() {
        //consultarAssessment();
        int confirma = JOptionPane.showConfirmDialog(null, "Do you really want to delete this GRADE?", "ATTENTION", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from  where idGrade=?";
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, txtIdAttendance.getText());
                pst.executeUpdate();
                eraseFieldsMain();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    private void btnAdminStudent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminStudent3ActionPerformed
        LecturerAttendance frmLecturerAtendance = new LecturerAttendance();
        frmLecturerAtendance.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdminStudent3ActionPerformed

    private void btnAdminFaculty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminFaculty3ActionPerformed
        lecturerGradeStudent frmLecturerGradeStudent = new lecturerGradeStudent();
        frmLecturerGradeStudent.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdminFaculty3ActionPerformed

    private void btnAdminBranch9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminBranch9ActionPerformed
        lecturerAssessment frmlecturerAssessment = new lecturerAssessment();
        frmlecturerAssessment.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdminBranch9ActionPerformed

    private void btnExit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit3ActionPerformed
        login frmLogin = new login();
        frmLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExit3ActionPerformed

    private void btnAdminBranch10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminBranch10ActionPerformed
        lecturerContactStudent FrmlecturerContactStudent = new lecturerContactStudent();
        FrmlecturerContactStudent.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdminBranch10ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void tbAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAttendanceMouseClicked
        eraseFieldsMain();
        txtIdStudent.setVisible(false);
        txtNameStudent.setVisible(false);
        txtSurnameStudent.setVisible(false);
        txtIdSubject.setVisible(false);
        txtTitleSubject.setVisible(false);
        tbStudent.setVisible(false);
        tbSubject.setVisible(false);
        //setar_camposAtt();
    }//GEN-LAST:event_tbAttendanceMouseClicked

    private void txtSurnameStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurnameStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameStudentActionPerformed

    private void tbStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStudentMouseClicked
        setar_camposSt();
    }//GEN-LAST:event_tbStudentMouseClicked

    private void tbSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSubjectMouseClicked
        setar_camposAs();
    }//GEN-LAST:event_tbSubjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminBranch10;
    private javax.swing.JButton btnAdminBranch9;
    private javax.swing.JButton btnAdminFaculty3;
    private javax.swing.JButton btnAdminStudent3;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEraseFields;
    private javax.swing.JButton btnExit3;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbAttendance;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTable tbSubject;
    private javax.swing.JLabel txtIdAttendance;
    private javax.swing.JTextField txtIdStudent;
    private javax.swing.JTextField txtIdSubject;
    private javax.swing.JTextField txtNameStudent;
    private javax.swing.JTextField txtSurnameStudent;
    private javax.swing.JTextField txtTitleSubject;
    private javax.swing.JTextField txtw1;
    private javax.swing.JTextField txtw10;
    private javax.swing.JTextField txtw11;
    private javax.swing.JTextField txtw12;
    private javax.swing.JTextField txtw13;
    private javax.swing.JTextField txtw14;
    private javax.swing.JTextField txtw15;
    private javax.swing.JTextField txtw2;
    private javax.swing.JTextField txtw3;
    private javax.swing.JTextField txtw4;
    private javax.swing.JTextField txtw5;
    private javax.swing.JTextField txtw6;
    private javax.swing.JTextField txtw7;
    private javax.swing.JTextField txtw8;
    private javax.swing.JTextField txtw9;
    // End of variables declaration//GEN-END:variables

    private void rs(String selectedItemStr) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
